### ISSUE TITLE
Crashing with remark-gfm#4.0.0

### ISSUE THREAD

**Issue by fabien0102-crabnebula** [andi23rosca/solid-markdown#26]
There are some breaking changes in remark-gfm, `solid-markdown` is only compatible with the version `3.0.1`.

Error with the `remark-gfm#4.0.0`:
![image](https://github.com/andi23rosca/solid-markdown/assets/138440652/4e6e97c5-3c75-4489-88d7-11095a5c7683)

### Workaround

Pin the version of `remark-gfm` on `3.0.1` and you are good to go 😉

**Comment by PidSS** [comment]
BTW, The Author wrote `"remark-gfm": "^3.0.1"` as dependencies in the `package.json`, but it was never used in the code.

I believe the entry was wrote for the purpose of testing but forgotten to be deleted.

While resolving this issue, could you also correct the dependency?

**Comment by andi23rosca** [comment]
I just released a new version `v.2.0.3`, I've updated all dependencies and fixed some type errors.
The latest `remark-gfm` is now supported
