### ISSUE TITLE
solid markdown not rendering blocks of code

### ISSUE THREAD

**Issue by Rotwo** [andi23rosca/solid-markdown#30]
I've been trying to render some code like this one: 

```cpp
#define LED_PIN 9
void setup() {
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);
}
void loop() {
  
}
```

but the code is not rendering any code format or colours.
Please tell me if I'm missing some setting to enable that or if it is unsupported.

**Comment by imkunet** [comment]
Hi there. I've had a go at this issue too. Here's a Stabkblitz link of a minimal example of how to do the syntax highlighting. 

https://stackblitz.com/edit/solidjs-templates-4lx1f8?file=src%2FApp.tsx

### Notes
- This is not using the `solid-markdown` package but is instead using the `@kunet/solid-markdown-but-updated` package instead. This is to fix some annoying TypeScript errors. If #31 is resolved, this will no longer be an issue to deal with.
- There is some hacky CSS in there to fix it all not rendering on one line. There is surely a better way to approach this but it looked good enough for me.
- The code supplied renders it on the client with a small wasm bundle. If this is not the desired behavior (i.e. SSR) there are other approaches that allow you to do SSR documented in [Shiki's documentation](https://shiki.style/guide/install#highlighter-usage).
- You must specify all languages you wish to render. You'll see it in the code.

**Comment by Rotwo** [comment]
Hey! I have finally fixed it, I ended using a third-party library called highlight.js which works surprisingly well with solid-markdown.
Also, thanks for letting me know the new npm package, it was really helpful to fix some types errors.
