### ISSUE TITLE
When providing a streaming content, everything re-renders all the time

### ISSUE THREAD

**Issue by baptisteArno** [andi23rosca/solid-markdown#32]
One thing that is cool with `react-markdown` is that even if you provide a content that is being streamed, what was already added to the DOM won't re-rendered again, allowing the user to interact with the existing text while the content is being streamed.

It seems this does not work the same with solid-markdown.

Reproduction:

```tsx
export const StreamingBubble = (props: Props) => {
  const [content, setContent] = createSignal<string>('')

  onMount(() => {
    setInterval(() => {
      setContent(content => content + 'new content')
    }, 100)
  })

  return <SolidMarkdown children={content()} />
}
```

If you select the text, whenever the component re-renders, the selection will be removed.

**Comment by andi23rosca** [comment]
Hey @baptisteArno, just fixed this in `v2.0.3`, there's now a `renderingStrategy` prop, you can pass `"reconcile"` to make it diff the ASTs and only re-render the parts of the DOM that changed.

See https://github.com/andi23rosca/solid-markdown?tab=readme-ov-file#rendering-strategy
