### ISSUE TITLE
Tables doesnt work

### ISSUE THREAD

**Issue by EntityB** [andi23rosca/solid-markdown#34]
Table syntax is not recognized. Tested simple table like: 

```
| a | b | 
| - | - | 
```

**Comment by andi23rosca** [comment]
Check out the demo example here: https://github.com/andi23rosca/solid-markdown/blob/main/dev/App.tsx

You should use the github flavored markdown if you most things you're accustomed to out of the box: [remark-gfm](https://github.com/remarkjs/remark-gfm)
